# Generated by Django 5.2 on 2025-06-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCompleto', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('mail', models.CharField(max_length=320)),
                ('celular', models.CharField(max_length=25)),
                ('tipoEmpleo', models.CharField(choices=[('1', 'Relacion de Dependencia'), ('2', 'Independiente')], max_length=1)),
                ('antiguedadLaboral', models.IntegerField()),
                ('ingresoBrutoMensual', models.IntegerField()),
                ('valorPropiedad', models.IntegerField()),
                ('ahorrosDisponibles', models.IntegerField()),
                ('plazoFinanciamiento', models.IntegerField()),
                ('montoCredito', models.FloatField()),
                ('montoCuota', models.FloatField()),
            ],
            options={
                'db_table': 'creditos',
            },
        ),
    ]
