# Generated by Django 5.2 on 2025-06-02 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulador', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitudes',
            old_name='mail',
            new_name='email',
        ),
    ]
